package plugin

import (
	"context"
	"time"
)

// Result is the structured output returned by a command plugin.
type Result struct {
	Success bool                   `json:"success"`
	Data    map[string]interface{} `json:"data,omitempty"`
	Output  string                 `json:"output,omitempty"`
	Error   string                 `json:"error,omitempty"`
}

// Event is passed to hook plugins when a subscribed system event occurs.
type Event struct {
	Type      string                 `json:"type"`
	Timestamp time.Time              `json:"timestamp"`
	AgentID   string                 `json:"agent_id,omitempty"`
	UserID    uint                   `json:"user_id,omitempty"`
	Payload   map[string]interface{} `json:"payload,omitempty"`
}

// Report is generated by report plugins.
type Report struct {
	Title   string `json:"title"`
	Format  string `json:"format"` // html, markdown, json
	Content []byte `json:"content"`
}

// Plugin is the base interface implemented by every ForgeC2 plugin.
type Plugin interface {
	Name() string
	Version() string
	Type() string // command, hook, report
	Description() string
	Init(ctx context.Context, config map[string]interface{}) error
	Shutdown() error
	IsEnabled() bool
}

// CommandPlugin executes custom tasks against an agent or the server.
type CommandPlugin interface {
	Plugin
	Execute(ctx context.Context, agentID string, params map[string]interface{}) (*Result, error)
}

// HookPlugin reacts to system events.
type HookPlugin interface {
	Plugin
	OnEvent(ctx context.Context, event Event) error
	SubscribedEvents() []string
}

// ReportPlugin generates reports in various formats.
type ReportPlugin interface {
	Plugin
	Generate(ctx context.Context, params map[string]interface{}) (*Report, error)
}
