package server

import (
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"github.com/forgec2/forgec2/internal/db"
	"github.com/gin-gonic/gin"
)

// TaskStatusPendingApproval marks tasks that were generated by the AI assistant
// and must be explicitly approved by an operator before the agent executes them.
// Beacon task claim only picks up tasks with status "pending", so these tasks
// stay dormant until an operator approves them.
const TaskStatusPendingApproval = "pending_approval"

// handleApproveTask promotes a pending_approval task to "pending" so the beacon
// can claim and execute it.
// POST /tasks/:taskId/approve
func (s *Server) handleApproveTask(c *gin.Context) {
	if !s.requireOperator(c) {
		return
	}

	var taskID uint
	if _, err := fmt.Sscanf(c.Param("taskId"), "%d", &taskID); err != nil {
		respondError(c, http.StatusBadRequest, "invalid task id")
		return
	}

	var task db.Task
	if err := s.db.First(&task, taskID).Error; err != nil {
		respondError(c, http.StatusNotFound, "task not found")
		return
	}
	if task.Status != TaskStatusPendingApproval {
		respondError(c, http.StatusBadRequest, fmt.Sprintf("task is %s, cannot approve", task.Status))
		return
	}

	// Two-man rule: the operator that created a dangerous task may not be
	// the one approving it. AI/automation/system-created tasks have no
	// human creator and may be approved by any operator.
	approver := s.currentUsername(c)
	if task.CreatedBy != "" && task.CreatedBy != "ai" && task.CreatedBy != "automation" && task.CreatedBy != "system" && approver != "" && task.CreatedBy == approver {
		respondError(c, http.StatusForbidden, "cannot approve your own task (two-man rule)")
		return
	}

	updates := map[string]interface{}{
		"status":      "pending",
		"approved_by": approver,
		"approved_at": time.Now(),
	}
	// Conditional flip, mirroring handleRejectTask/handleCancelTask: a stale
	// read here let approve resurrect a task another operator had just
	// rejected or cancelled (dangerous types would then execute).
	res := s.db.Model(&db.Task{}).
		Where("id = ? AND status IN ?", taskID, []string{TaskStatusPendingApproval}).
		Updates(updates)
	if res.Error != nil {
		slog.Error("Failed to approve task", "task", taskID, "err", res.Error)
		respondError(c, http.StatusInternalServerError, "failed to approve task")
		return
	}
	if res.RowsAffected == 0 {
		respondError(c, http.StatusConflict, "task is no longer awaiting approval")
		return
	}
	task.Status = "pending"
	task.ApprovedBy = approver

	slog.Info("Task approved", "agent_id", task.AgentID, "task", taskID, "type", task.Type)
	s.LogAuditRecord(c, "approve_task", "agent_id", task.AgentID, fmt.Sprintf("Approved task #%d (%s)", taskID, task.Type), true, nil)
	s.broadcastTaskUpdate(task.AgentID, task)
	c.JSON(http.StatusOK, gin.H{"success": true, "message": "Task approved and queued for execution"})
}

// handleRejectTask cancels a pending_approval task so it never reaches the agent.
// POST /tasks/:taskId/reject
func (s *Server) handleRejectTask(c *gin.Context) {
	if !s.requireOperator(c) {
		return
	}

	var taskID uint
	if _, err := fmt.Sscanf(c.Param("taskId"), "%d", &taskID); err != nil {
		respondError(c, http.StatusBadRequest, "invalid task id")
		return
	}

	var task db.Task
	if err := s.db.First(&task, taskID).Error; err != nil {
		respondError(c, http.StatusNotFound, "task not found")
		return
	}
	if task.Status != TaskStatusPendingApproval {
		respondError(c, http.StatusBadRequest, fmt.Sprintf("task is %s, cannot reject", task.Status))
		return
	}

	// Snapshot the pre-reject status, then flip to cancelled with a
	// conditional update so a concurrent approve/cancel cannot race us.
	priorStatus := task.Status

	result := s.db.Model(&db.Task{}).
		Where("id = ? AND status IN ?", taskID, []string{"pending", TaskStatusPendingApproval}).
		Updates(map[string]interface{}{
			"status": "cancelled",
			"error":  "rejected by operator",
		})
	if result.Error != nil {
		slog.Error("Failed to reject task", "task", taskID, "err", result.Error)
		respondError(c, http.StatusInternalServerError, "failed to reject task")
		return
	}
	if result.RowsAffected == 0 {
		currentStatus := priorStatus
		var fresh db.Task
		if err := s.db.First(&fresh, "id = ?", taskID).Error; err == nil {
			currentStatus = fresh.Status
		}
		respondError(c, http.StatusConflict, fmt.Sprintf("task is now %s, cannot reject", currentStatus))
		return
	}

	task.Status = "cancelled"
	task.Error = "rejected by operator"

	// The task occupied a pending-counter slot since creation (pending_approval
	// tasks are counted); release it now that it will never be claimed.
	if priorStatus == "pending" || priorStatus == TaskStatusPendingApproval {
		s.decPendingTasks(task.AgentID)
	}

	slog.Info("Task rejected", "agent_id", task.AgentID, "task", taskID, "type", task.Type)
	s.LogAuditRecord(c, "reject_task", "agent_id", task.AgentID, fmt.Sprintf("Rejected task #%d (%s)", taskID, task.Type), true, nil)
	s.broadcastTaskUpdate(task.AgentID, task)
	c.JSON(http.StatusOK, gin.H{"success": true, "message": "Task rejected"})
}
