package middleware

import (
	"net/http"
	"time"

	"github.com/forgec2/forgec2/internal/config"
	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
	"golang.org/x/crypto/bcrypt"
)

var jwtSecret []byte

const (
	JWTExpiry    = 24 * time.Hour
	CookieMaxAge = 86400
)

// Claims for JWT
type Claims struct {
	Username string `json:"username"`
	ClientIP string `json:"client_ip"`
	jwt.RegisteredClaims
}

// InitJWTSecret initializes the JWT secret from config
func InitJWTSecret(cfg *config.Config) {
	secret := cfg.Server.JWTSecret
	if secret == "" {
		// Should have been generated by config.Load; this is a safeguard
		panic("JWT secret is empty after config load - security misconfiguration")
	}
	jwtSecret = []byte(secret)
}

// clientIP extracts the real client IP from request
func clientIP(c *gin.Context) string {
	ip := c.ClientIP()
	if ip == "" || ip == "::1" {
		ip = c.Request.Header.Get("X-Forwarded-For")
	}
	if ip == "" {
		ip = c.Request.RemoteAddr
	}
	return ip
}

// AuthRequired middleware for web UI
func AuthRequired(cfg *config.Config) gin.HandlerFunc {
	return func(c *gin.Context) {
		tokenStr, err := c.Cookie("forgec2_session")
		if err != nil {
			c.Redirect(http.StatusFound, "/login")
			c.Abort()
			return
		}

		token, err := jwt.ParseWithClaims(tokenStr, &Claims{}, func(token *jwt.Token) (interface{}, error) {
			return jwtSecret, nil
		})
		if err != nil || !token.Valid {
			c.SetCookie("forgec2_session", "", -1, "/", "", false, true)
			c.Redirect(http.StatusFound, "/login")
			c.Abort()
			return
		}

		// Validate client IP binding
		if claims, ok := token.Claims.(*Claims); ok {
			c.Set("user", claims.Username)
			if claims.ClientIP != "" && claims.ClientIP != clientIP(c) {
				c.SetCookie("forgec2_session", "", -1, "/", "", false, true)
				c.Redirect(http.StatusFound, "/login")
				c.Abort()
				return
			}
		}

		c.Next()
	}
}

// GenerateToken creates a JWT for the session
func GenerateToken(username, clientIP string) (string, error) {
	claims := &Claims{
		Username: username,
		ClientIP: clientIP,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(JWTExpiry)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString(jwtSecret)
}

// CheckPassword compares hash
func CheckPassword(hash, password string) bool {
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) == nil
}

// HashPassword for initial setup
func HashPassword(password string) (string, error) {
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	return string(hash), err
}
