package report

import (
	"fmt"
	"time"

	"github.com/forgec2/forgec2/internal/db"
	"github.com/jung-kurt/gofpdf"
	"gorm.io/gorm"
)

// PDFReport generates a PDF report for engagement reporting.
type PDFReport struct {
	Title    string
	Operator string
	Date     time.Time
	Sections []ReportSection
}

type ReportSection struct {
	Title   string
	Content string
	Table   [][]string
}

// Generate creates a PDF report and returns the file path.
func (r *PDFReport) Generate(outputPath string) error {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)

	// Title page
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 24)
	pdf.Cell(0, 80, "")
	pdf.Cell(0, 10, r.Title)
	pdf.Ln(15)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(0, 10, fmt.Sprintf("Operator: %s", r.Operator))
	pdf.Ln(8)
	pdf.Cell(0, 10, fmt.Sprintf("Date: %s", r.Date.Format("2006-01-02 15:04:05")))
	pdf.Ln(8)
	pdf.Cell(0, 10, fmt.Sprintf("Generated by ForgeC2"))
	pdf.Ln(20)

	// Classification
	pdf.SetFont("Arial", "B", 14)
	pdf.SetTextColor(200, 0, 0)
	pdf.Cell(0, 10, "CLASSIFICATION: TLP:RED")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(15)

	// Sections
	for _, section := range r.Sections {
		pdf.AddPage()
		pdf.SetFont("Arial", "B", 16)
		pdf.Cell(0, 10, section.Title)
		pdf.Ln(12)

		if section.Content != "" {
			pdf.SetFont("Arial", "", 11)
			pdf.MultiCell(0, 6, section.Content, "", "", false)
			pdf.Ln(8)
		}

		if len(section.Table) > 0 {
			pdf.SetFont("Arial", "B", 10)
			// Header
			for _, cell := range section.Table[0] {
				pdf.CellFormat(40, 8, cell, "1", 0, "", false, 0, "")
			}
			pdf.Ln(-1)

			// Rows
			pdf.SetFont("Arial", "", 9)
			for _, row := range section.Table[1:] {
				for _, cell := range row {
					display := cell
					if len(display) > 30 {
						display = display[:30] + "..."
					}
					pdf.CellFormat(40, 7, display, "1", 0, "", false, 0, "")
				}
				pdf.Ln(-1)
			}
		}
	}

	return pdf.OutputFileAndClose(outputPath)
}

// GenerateEngagementReport creates a full engagement report from database data.
func GenerateEngagementReport(database *gorm.DB, outputPath, operator string) error {
	// Gather data
	var agents []db.Implant
	database.Select("id, hostname, ip, os, username, status, last_seen").Find(&agents)

	var tasks []db.Task
	database.Select("id, agent_id, type, command, status, created_at").Order("created_at desc").Limit(100).Find(&tasks)

	var creds []db.CredentialEntry
	database.Select("agent_id, domain, username, type, source, created_at").Order("created_at desc").Limit(100).Find(&creds)

	var auditLogs []db.AuditLog
	database.Order("created_at desc").Limit(200).Find(&auditLogs)

	report := &PDFReport{
		Title:    "ForgeC2 Engagement Report",
		Operator: operator,
		Date:     time.Now(),
	}

	// Executive Summary
	report.Sections = append(report.Sections, ReportSection{
		Title: "Executive Summary",
		Content: fmt.Sprintf(
			"This report covers engagement activity from ForgeC2.\n\n"+
				"Total Agents: %d\n"+
				"Total Tasks Executed: %d\n"+
				"Credentials Collected: %d\n"+
				"Audit Events: %d\n",
			len(agents), len(tasks), len(creds), len(auditLogs),
		),
	})

	// Agents section
	agentTable := [][]string{{"Hostname", "IP", "OS", "Username", "Status"}}
	for _, a := range agents {
		agentTable = append(agentTable, []string{a.Hostname, a.IP, a.OS, a.Username, a.Status})
	}
	report.Sections = append(report.Sections, ReportSection{
		Title: "Compromised Hosts",
		Table:  agentTable,
	})

	// Tasks section
	taskTable := [][]string{{"Agent", "Type", "Command", "Status"}}
	for _, t := range tasks {
		cmd := t.Command
		if len(cmd) > 40 {
			cmd = cmd[:40] + "..."
		}
		taskTable = append(taskTable, []string{t.AgentID[:8], t.Type, cmd, t.Status})
	}
	report.Sections = append(report.Sections, ReportSection{
		Title: "Task Execution Log",
		Table:  taskTable,
	})

	// Credentials section
	credTable := [][]string{{"Agent", "Domain", "Username", "Type", "Source"}}
	for _, c := range creds {
		credTable = append(credTable, []string{c.AgentID[:8], c.Domain, c.Username, c.Type, c.Source})
	}
	report.Sections = append(report.Sections, ReportSection{
		Title: "Collected Credentials",
		Table:  credTable,
	})

	// MITRE ATT&CK Mapping section
	attackTable := [][]string{{"Technique", "Tactic", "Tasks"}}
	techniqueCount := map[string]int{}
	for _, t := range tasks {
		if tech := mapTaskToATTCK(t.Type); tech != "" {
			techniqueCount[tech]++
		}
	}
	for tech, count := range techniqueCount {
		tactic := getTacticForTechnique(tech)
		attackTable = append(attackTable, []string{tech, tactic, fmt.Sprintf("%d", count)})
	}
	report.Sections = append(report.Sections, ReportSection{
		Title: "MITRE ATT&CK Mapping",
		Table:  attackTable,
	})

	return report.Generate(outputPath)
}

// mapTaskToATTCK maps a task type to a MITRE ATT&CK technique.
func mapTaskToATTCK(taskType string) string {
	mapping := map[string]string{
		"shell":           "T1059 - Command and Scripting Interpreter",
		"screenshot":      "T1113 - Screen Capture",
		"keylogger_start": "T1056.001 - Keylogging",
		"creds_dump":      "T1003 - OS Credential Dumping",
		"download":        "T1041 - Exfiltration Over C2 Channel",
		"upload":          "T1105 - Ingress Tool Transfer",
		"privesc_check":   "T1068 - Exploitation for Privilege Escalation",
		"ps":              "T1057 - Process Discovery",
		"ls":              "T1083 - File and Directory Discovery",
		"token_steal":     "T1134.001 - Token Impersonation",
		"set_sleep":       "T1029 - Scheduled Transfer",
		"inject":          "T1055 - Process Injection",
		"browser_steal":   "T1539 - Steal Web Session Cookie",
	}
	return mapping[taskType]
}

func getTacticForTechnique(technique string) string {
	tacticMap := map[string]string{
		"T1059":       "Execution",
		"T1113":       "Collection",
		"T1056.001":   "Collection",
		"T1003":       "Credential Access",
		"T1041":       "Exfiltration",
		"T1105":       "Command and Control",
		"T1068":       "Privilege Escalation",
		"T1057":       "Discovery",
		"T1083":       "Discovery",
		"T1134.001":   "Defense Evasion",
		"T1029":       "Command and Control",
		"T1055":       "Defense Evasion",
		"T1539":       "Credential Access",
	}
	for k, v := range tacticMap {
		if len(technique) >= len(k) && technique[:len(k)] == k {
			return v
		}
	}
	return "Multiple"
}
