/**
 * Permission helpers for role-based UI gating.
 *
 * The permission strings are the wire values of /api/me → data.permissions,
 * which mirror the backend permission constants in internal/db/models.go
 * (see ./permission-keys.ts, generated by `npm run gen:permissions`).
 * Admin users receive the full permission set, so no role special-casing is
 * needed here.
 */
import type { PermissionKey } from "./permission-keys";

export type { PermissionKey };

export type Permissions = readonly PermissionKey[] | null | undefined;

/** True when the user holds the exact permission. */
export function can(permissions: Permissions, perm: PermissionKey): boolean {
  if (!permissions) return false;
  return permissions.includes(perm);
}

/** True when the user holds at least one of the given permissions. */
export function canAny(permissions: Permissions, perms: readonly PermissionKey[]): boolean {
  if (!permissions || perms.length === 0) return false;
  return perms.some((p) => permissions.includes(p));
}

/** True when the user holds every one of the given permissions. */
export function canAll(permissions: Permissions, perms: readonly PermissionKey[]): boolean {
  if (!permissions) return false;
  return perms.every((p) => permissions.includes(p));
}